name = "builtbyrays-cfo-os"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.production]
name = "builtbyrays-cfo-os-prod"

[env.staging]
name = "builtbyrays-cfo-os-staging"

[[pages]]
name = "BuiltByRays CFO OS"
source = "." 